package com.taskmanager.entity;

import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Table(name = "tasks")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Task {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(description = "Task id, generated by the server.", accessMode = Schema.AccessMode.READ_ONLY, example = "1")
    private Long id;

    @Column(nullable = false)
    @Schema(description = "Task title.", example = "Fazer compras")
    private String title;

    @Schema(description = "Optional task description.", example = "Leite, pão, ovos")
    private String description;

    @Column(nullable = false)
    @Schema(description = "Whether the task is completed.", example = "false")
    private Boolean completed = false;

    @Column(name = "created_at", nullable = false, updatable = false)
    @Schema(description = "Timestamp the task was created, set automatically by the server.", accessMode = Schema.AccessMode.READ_ONLY, example = "2026-07-18T10:30:00")
    private LocalDateTime createdAt;

    @Column(name = "updated_at")
    @Schema(description = "Timestamp the task was last updated, set automatically by the server.", accessMode = Schema.AccessMode.READ_ONLY, example = "2026-07-18T10:30:00")
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
    
}
